### PR TITLE
Update Ruby & Bundler on Travis CI; Drop support Ruby 2.2

### PR DESCRIPTION
**Pull request by ybiquitous**
PR #16 Travis build failed due to Bundler 2.
See https://travis-ci.org/pocke/exception_notification-bugsnag/builds/490934345

So, this PR updates Ruby & Bundler used on Travis CI.

For Bundler2 on Travis CI, please see [this Travis document](https://docs.travis-ci.com/user/languages/ruby/#bundler-20).

In addition, this PR **drops support for Ruby 2.2** (which has been EOL).

### CODE REVIEW

**Comment by ybiquitous** [comment]
Oooops! Bundler 2 removed support for Ruby 2.2.
https://bundler.io/guides/bundler_2_upgrade.html#will-bundler-2-have-any-other-notable-changes

Only the build for Ruby 2.2.10 failed. 😭 
https://travis-ci.org/pocke/exception_notification-bugsnag/jobs/490936957#L491

**Comment by pocke** [comment]
Ruby 2.2 has been EOL.
https://www.ruby-lang.org/en/news/2018/06/20/support-of-ruby-2-2-has-ended/
So I think we can drop supporting Ruby 2.2.

**Comment by ybiquitous** [comment]
@pocke Thanks for your quick response. I agree with dropping support for Ruby 2.2! 👍 

I will do it on this PR 💪 Please tell me if there are any problems. 🙏

**Comment by ybiquitous** [comment]
OK, CI becomes all green! I'm ready to edit `CHANGELOG.md` on this PR if someone hopes.

**Review by pocke — APPROVED** [review]
Thank you!

CHANGELOG entry, and specifing `required_ruby_version` to gemspec are better.
https://guides.rubygems.org/specification-reference/#required_ruby_version=

**Comment by ybiquitous** [comment]
@pocke Thanks a lot for your help! I don't know `required_ruby_version`, which is a nice feature!

I updated Changelog and added `required_ruby_version`, and then CI became all green.
I think this PR is ready to merge!

**Pull request merged**
